program: terrain-diffusion/inference/evaluation/evaluate_sr_fid.py
method: bayes
metric:
  name: fid
  goal: minimize
parameters:
  # Main model sigma relative
  main-sigma-rel:
    distribution: log_uniform_values
    min: 0.015
    max: 0.15
  
  # Guide model sigma relative
  guide-sigma-rel:
    distribution: log_uniform_values
    min: 0.015
    max: 0.15
  
  # Guide EMA step
  guide-ema-step:
    distribution: q_log_uniform_values
    min: 512
    max: 15360
    q: 512

  # Guidance scale
  guidance-scale:
    distribution: uniform
    min: 1.0
    max: 2.0

  # Fixed parameters
  main-config:
    value: "configs/diffusion_x8/diffusion_x8_64-3.cfg"  # Replace with your config path
  guide-config:
    value: "configs/diffusion_x8/diffusion_x8_32-2.cfg"  # Replace with your config path
  log-samples:
    value: 2048
  max-samples:
    value: 2048
  batch-size:
    value: 64
  scheduler-steps:
    value: 15
command:
  - env
  - PYTHONPATH=terrain-diffusion
  - accelerate
  - launch
  - ${program}
  - ${args}